### ISSUE TITLE
1.12 Update

### ISSUE THREAD

**Issue by dwatsX** [Sqeegie/GoldIsMoney#2]
Thanks so much for the update. Upon updating it seems that GoldIsMoney is using bank accounts separate from Vault. For example, a player who uses /bal sees a separate balance tied to their Vault balance. So if they have a Vault balance of $10 and the player has 5 emeralds in their inventory, /bal returns $10 (I use emeralds as currency, and the plugin is configured as such). If the player uses /money or /balance, the plugin then properly prints the emerald balance into the chat, and will say that they have 5 emeralds. However, if a player tries to use their money, it is deducted from the vault balance (from the $10) and the emeralds in their inventory are not taken.
I noticed from the source code that only /money and /balance are used to return the emerald amount in a player's inventory, which I am cool with - but I'm wondering if I'm missing something - in order to get the server to take their emerald money instead of vault money? Any insight you've got would be greatly appreciated!

**Comment by Sqeegie** [comment]
Your problem isn't caused by anything you're doing, or not doing. I've been using the legacy, 1.0 builds of GoldIsMoney for this particularly repository as it fit my personal needs better. However, by doing so, it does occasionally cause problems, as you can tell. Especially with newer plugins and recent Bukkit builds. In light of this, as well as the fact I no longer require GoldIsMoney for personal needs, I've updated the repo to the newer 2.0 builds. This should, theoretically, resolve your dilemma. Head over to the releases and download the latest build.

**Comment by Sqeegie** [comment]
I'll keep this issue open until you confirm the problem has been resolved.

**Comment by dwatsX** [comment]
Thanks I'll build this against spigot 1.12 and Vault and see if she works!

**Comment by dwatsX** [comment]
Well it seems to not want to load at all, it seems to be pointing to an issue with the plugin.yml file. Any thoughts?

`[17:23:15] [Server thread/ERROR]: Could not load 'plugins/GoldisMoney.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:152) ~[spigot.jar:git-Spigot-cd6ba67-732911e]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [spigot.jar:git-Spigot-cd6ba67-732911e]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:302) [spigot.jar:git-Spigot-cd6ba67-732911e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot.jar:git-Spigot-cd6ba67-732911e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-cd6ba67-732911e]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml`

**Comment by Sqeegie** [comment]
Did you build it yourself, or download the pre-built version?

**Comment by dwatsX** [comment]
Built it myself, I didn't see yours hang on

**Comment by dwatsX** [comment]
Yeah when I go to download the ZIP it just contains an un-built version so I assumed I was to build it myself.

**Comment by Sqeegie** [comment]
You're going to the release page (https://github.com/Sqeegie/GoldIsMoney/releases), right?

**Comment by dwatsX** [comment]
Ok my bad I downloaded the wrong thing, I'll test again

**Comment by dwatsX** [comment]
Ok this is loading properly, but is doing the same thing as before. Looks like this version includes the /bal command also, but does not seem to tie into Vault. When doing /bal, /balance, or /money, it returns "You have X emeralds" in chat, where X is the amount of emeralds in your inventory. When buying or selling, though, money is taken from/deposited to the typical Vault balance, which I can see in /ebal.

**Comment by Sqeegie** [comment]
Hmm. Let me look into it. Would you kindly provide a list of plugins, as well as your config settings?

**Comment by dwatsX** [comment]
Sure 

name-singular: emerald
name-plural: emeralds
format-singular: '%n emerald'
format-plural: '%n emeralds'
allow-creative: false
currency-family: emerald
text-balance: '&3You have &6%g&3.'
text-balance-perms-fail: '&6You cannot use item currency at this time.'
text-reloaded: '&3GoldIsMoney has reloaded.'
text-admin-perms-fail: '&6You do not have admin privs for GoldIsMoney.'
fractional-digits: 0
custom-currency: {}
allow-fake-players: true
allow-banks: true
autocreate-accounts: true
autocreated-bank-owner: flobi

**Comment by dwatsX** [comment]
![2017-06-15_18 19 40](https://user-images.githubusercontent.com/24707476/27204117-3b994e32-51f7-11e7-8acf-3c26db1ab8d6.png)

**Comment by Sqeegie** [comment]
Alright, I believe the issue has been resolved. Download the latest release and test it out.

**Comment by dwatsX** [comment]
This seems to be working correctly now! Thanks so much for your help! I'll continue using the plugin and report any issues if they arise. Thanks again.
